### ISSUE TITLE
[Bug]: Upgrade button didn't work 

### ISSUE THREAD

**Issue by andersondn** [coollabsio/coolify#1239]
### Description

I have the version v4.0.0-beta.25 installed and I want to upgrade to the latest beta version. 

When I click on the button to upgrade, it shows a success toast saying "Upgrading to next version..." but nothing happens.

Is it possible to upgrade manually? 

### Minimal Reproduction (if possible, example repository)

Upgrade Coolify version by clicking on upgrade button 

### Version

v4.0.0-beta.25

**Comment by andrasbacsai** [comment]
It is fixed now. 

Yes. Just execute the installation script again. `curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash`

**Comment by raphaelbernhart** [comment]
Not fixed for me.

I tried to update via the button and via your proposed solution.

![image](https://github.com/coollabsio/coolify/assets/48283236/8887c98b-078a-4c58-858f-6c67d2351703)
![image](https://github.com/coollabsio/coolify/assets/48283236/46b1e5e6-a062-4524-b194-d63615826813)
