### ISSUE TITLE
[Bug]: InstanceAutoUpdateJob failed

### ISSUE THREAD

**Issue by luckydonald** [coollabsio/coolify#1958]
### Description

The autoupdate seems broken, it's sending issues on the telegram plugin.

error parsing HTTP 429 response body: invalid character 'S' looking for beginning of value: "Server capacity exceeded.\n"

### Minimal Reproduction (if possible, example repository)

I don't really know.

##### 11:10

coolify-helper
Digest: sha256:4770886f7214920a14c97f408c0719b1f4a39c6839dbe0d152a33ca243ebea8b
Status: Image is up to date for ghcr.io/coollabsio/coolify-helper:latest
time="2024-04-09T09:10:04Z" level=warning msg="/data/coolify/source/docker-compose.yml: version is obsolete"
time="2024-04-09T09:10:04Z" level=warning msg="/data/coolify/source/docker-compose.prod.yml: version is obsolete"
 coolify Pulling 
 redis Pulling 
 soketi Pulling 
 postgres Pulling 
 postgres Pulled 
 redis Pulled 
 soketi Pulled 
toomanyrequests: retry-after: 674.813µs, allowed: 44000/minute

----

##### 11:20
InstanceAutoUpdateJob failed: latest: Pulling from coollabsio/coolify-helper
Digest: sha256:4770886f7214920a14c97f408c0719b1f4a39c6839dbe0d152a33ca243ebea8b
Status: Image is up to date for ghcr.io/coollabsio/coolify-helper:latest
time="2024-04-09T09:20:06Z" level=warning msg="/data/coolify/source/docker-compose.yml: version is obsolete"
time="2024-04-09T09:20:06Z" level=warning msg="/data/coolify/source/docker-compose.prod.yml: version is obsolete"
 coolify Pulling 
 redis Pulling 
 postgres Pulling 
 soketi Pulling 
 redis Pulled 
 postgres Pulled 
 soketi Error 
toomanyrequests: retry-after: 680.118µs, allowed: 44000/minute

----

##### 11:30
InstanceAutoUpdateJob failed: latest: Pulling from coollabsio/coolify-helper
Digest: sha256:4770886f7214920a14c97f408c0719b1f4a39c6839dbe0d152a33ca243ebea8b
Status: Image is up to date for ghcr.io/coollabsio/coolify-helper:latest
time="2024-04-09T09:30:05Z" level=warning msg="/data/coolify/source/docker-compose.yml: version is obsolete"
time="2024-04-09T09:30:05Z" level=warning msg="/data/coolify/source/docker-compose.prod.yml: version is obsolete"
 postgres Pulling 
 redis Pulling 
 soketi Pulling 
 coolify Pulling 
 postgres Pulled 
 redis Pulled 
 soketi Pulled 
 2ab09b027e7f Already exists 
 9a37c607e3b8 Already exists 
 e7dee23fc229 Already exists 
 36be7b77e484 Already exists 
 c2264024df91 Already exists 
 5bd06a8578b4 Already exists 
 1c9860225ba8 Already exists 
 c139b40b7ffb Already exists 
 3505538d7b34 Already exists 
 ff2e202e8afe Already exists 
 31a43c73e3cd Already exists 
 4985c56ea1c5 Already exists 
 ab485b130f06 Already exists 
 9ddc29713d11 Already exists 
 4f2445dc3105 Already exists 
 07ff8107d10b Already exists 
 4f4fb700ef54 Already exists 
 343accc3ea62 Pulling fs layer 
 91dc37572ce4 Pulling fs layer 
 09e0edea32f3 Pulling fs layer 
 73c8673a655d Pulling fs layer 
 095ee589639c Pulling fs layer 
 25af5b11bed0 Pulling fs layer 
 4500d9da6e2b Pulling fs layer 
 3e7f118f8f0a Pulling fs layer 
 633da2ff5904 Pulling fs layer 
 7a35cf7ee4e6 Pulling fs layer 
 9e652294f32a Pulling fs layer 
 89cc8c75d87e Pulling fs layer 
 1082368ff6d1 Pulling fs layer 
 7fcf07ceaafd Pulling fs layer 
 0bb98aabbe64 Pulling fs layer 
 5bbe5c085142 Pulling fs layer 
 762cbade1521 Pulling fs layer 
 c779c70538a5 Pulling fs layer 
 d3dd1691b833 Pulling fs layer 
 4f4fb700ef54 Pulling fs layer 
 78533cd43193 Pulling fs layer 
 14962fde825d Pulling fs layer 
 73c8673a655d Waiting 
 095ee589639c Waiting 
 25af5b11bed0 Waiting 
 4500d9da6e2b Waiting 
 3e7f118f8f0a Waiting 
 633da2ff5904 Waiting 
 c779c70538a5 Waiting 
 7a35cf7ee4e6 Waiting 
 d3dd1691b833 Waiting 
 9e652294f32a Waiting 
 4f4fb700ef54 Waiting 
 89cc8c75d87e Waiting 
 1082368ff6d1 Waiting 
 7fcf07ceaafd Waiting 
 0bb98aabbe64 Waiting 
 78533cd43193 Waiting 
 5bbe5c085142 Waiting 
 762cbade1521 Waiting 
 14962fde825d Waiting 
 09e0edea32f3 Downloading ==================>                                  1.378kB/3.649kB
 09e0edea32f3 Downloading ==================================================>  3.649kB/3.649kB
 09e0edea32f3 Verifying Checksum 
 09e0edea32f3 Download complete 
 91dc37572ce4 Downloading >                                                      213kB/20.42MB
 91dc37572ce4 Downloading ======>                                              2.547MB/20.42MB
 343accc3ea62 Downloading >                                                    360.4kB/35.23MB
 91dc37572ce4 Downloading ==========>                                          4.249MB/20.42MB
 343accc3ea62 Downloading ==>                                                  1.442MB/35.23MB
 73c8673a655d Downloading 
toomanyrequests: retry-after: 752.627µs, allowed: 44000/minute

----

# 12:40
InstanceAutoUpdateJob failed: latest: Pulling from coollabsio/coolify-helper
Digest: sha256:4770886f7214920a14c97f408c0719b1f4a39c6839dbe0d152a33ca243ebea8b
Status: Image is up to date for ghcr.io/coollabsio/coolify-helper:latest
time="2024-04-09T10:40:05Z" level=warning msg="/data/coolify/source/docker-compose.yml: version is obsolete"
time="2024-04-09T10:40:05Z" level=warning msg="/data/coolify/source/docker-compose.prod.yml: version is obsolete"
 coolify Pulling 
 postgres Pulling 
 redis Pulling 
 soketi Pulling 
 postgres Pulled 
 redis Pulled 
 soketi Pulled 
toomanyrequests: retry-after: 812.977µs, allowed: 44000/minute

----

##### 12:50
InstanceAutoUpdateJob failed: latest: Pulling from coollabsio/coolify-helper
Digest: sha256:4770886f7214920a14c97f408c0719b1f4a39c6839dbe0d152a33ca243ebea8b
Status: Image is up to date for ghcr.io/coollabsio/coolify-helper:latest
time="2024-04-09T10:50:04Z" level=warning msg="/data/coolify/source/docker-compose.yml: version is obsolete"
time="2024-04-09T10:50:04Z" level=warning msg="/data/coolify/source/docker-compose.prod.yml: version is obsolete"
 soketi Pulling 
 coolify Pulling 
 postgres Pulling 
 redis Pulling 
 redis Pulled 
 postgres Pulled 
 soketi Pulled 
 2ab09b027e7f Already exists 
 9a37c607e3b8 Already exists 
 e7dee23fc229 Already exists 
 36be7b77e484 Already exists 
 c2264024df91 Already exists 
 5bd06a8578b4 Already exists 
 1c9860225ba8 Already exists 
 c139b40b7ffb Already exists 
 3505538d7b34 Already exists 
 ff2e202e8afe Already exists 
 31a43c73e3cd Already exists 
 4985c56ea1c5 Already exists 
 ab485b130f06 Already exists 
 9ddc29713d11 Already exists 
 4f2445dc3105 Already exists 
 07ff8107d10b Already exists 
 4f4fb700ef54 Already exists 
 4cbffc6e304e Pulling fs layer 
 0643f46a2213 Pulling fs layer 
 2ca58c5d0b90 Pulling fs layer 
 e1055f09da5e Pulling fs layer 
 b1ad9c614895 Pulling fs layer 
 a22a08f8b6ef Pulling fs layer 
 f085aa527676 Pulling fs layer 
 344bdbdecadc Pulling fs layer 
 b0b80cb7ac6c Pulling fs layer 
 17a7fc4f221d Pulling fs layer 
 4d336278c72c Pulling fs layer 
 a8827479f3e1 Pulling fs layer 
 3efdcf61bfee Pulling fs layer 
 b50516d9be9d Pulling fs layer 
 5d31fba546d7 Pulling fs layer 
 5aa4df3f3858 Pulling fs layer 
 7204d3434b2f Pulling fs layer 
 34e29d765607 Pulling fs layer 
 6398b59bd1a0 Pulling fs layer 
 4f4fb700ef54 Pulling fs layer 
 30bb0ae3fea1 Pulling fs layer 
 1a4a17e400e1 Pulling fs layer 
 a22a08f8b6ef Waiting 
 f085aa527676 Waiting 
 344bdbdecadc Waiting 
 b0b80cb7ac6c Waiting 
 17a7fc4f221d Waiting 
 4d336278c72c Waiting 
 a8827479f3e1 Waiting 
 3efdcf61bfee Waiting 
 b50516d9be9d Waiting 
 5d31fba546d7 Waiting 
 5aa4df3f3858 Waiting 
 7204d3434b2f Waiting 
 34e29d765607 Waiting 
 6398b59bd1a0 Waiting 
 30bb0ae3fea1 Waiting 
 4f4fb700ef54 Waiting 
 e1055f09da5e Waiting 
 b1ad9c614895 Waiting 
 1a4a17e400e1 Waiting 
 4cbffc6e304e Downloading >                                                    360.4kB/35.23MB
 2ca58c5d0b90 Downloading ==================>                                  1.378kB/3.647kB
 2ca58c5d0b90 Downloading ==================================================>  3.647kB/3.647kB
 2ca58c5d0b90 Verifying Checksum 
 2ca58c5d0b90 Download complete 
 0643f46a2213 Downloading >                                                    211.3kB/20.42MB
 4cbffc6e304e Downloading ===>                                                 2.519MB/35.23MB
 0643f46a2213 Downloading ==>                                                  850.3kB/20.42MB
 4cbffc6e304e Downloading ======>                                              4.676MB/35.23MB
 0643f46a2213 Downloading ===>                                                 1.489MB/20.42MB
 4cbffc6e304e Downloading =========>                                           6.839MB/35.23MB
 e1055f09da5e Downloading 
toomanyrequests: retry-after: 346.034µs, allowed: 44000/minute

----

##### 14:00
InstanceAutoUpdateJob failed: latest: Pulling from coollabsio/coolify-helper
Digest: sha256:4770886f7214920a14c97f408c0719b1f4a39c6839dbe0d152a33ca243ebea8b
Status: Image is up to date for ghcr.io/coollabsio/coolify-helper:latest
time="2024-04-09T12:00:05Z" level=warning msg="/data/coolify/source/docker-compose.yml: version is obsolete"
time="2024-04-09T12:00:05Z" level=warning msg="/data/coolify/source/docker-compose.prod.yml: version is obsolete"
 soketi Pulling 
 postgres Pulling 
 coolify Pulling 
 redis Pulling 
 redis Error 
 postgres Error 
 soketi Error 
 coolify Error 
Error response from daemon: Head "https://registry-1.docker.io/v2/library/redis/manifests/alpine": error parsing HTTP 429 response body: invalid character 'S' looking for beginning of value: "Server capacity exceeded.\n"

### Version

v4.0.0-beta.251

**Comment by andrasbacsai** [comment]
I've seen this issue as well. It was a temporary error on Docker Hub side, not on Coolify. It is resolved now.

**Comment by VCasecnikovs** [comment]
@andrasbacsai 
Hi, it is still not resolved

InstanceAutoUpdateJob failed: latest: Pulling from coollabsio/coolify-helper
Digest: sha256:4770886f7214920a14c97f408c0719b1f4a39c6839dbe0d152a33ca243ebea8b
Status: Image is up to date for ghcr.io/coollabsio/coolify-helper:latest
time="2024-04-17T12:40:07Z" level=warning msg="/data/coolify/source/docker-compose.yml: version is obsolete"
time="2024-04-17T12:40:07Z" level=warning msg="/data/coolify/source/docker-compose.prod.yml: version is obsolete"
 coolify Pulling 
 soketi Pulling 
 postgres Pulling 
 redis Pulling 
 coolify Error 
 postgres Error 
 redis Error 
 soketi Error 
Error response from daemon: toomanyrequests: retry-after: 1.138091ms, allowed: 44000/minute

**Comment by idealadarsh** [comment]
I am also facing the same issue.

InstanceAutoUpdateJob failed: latest: Pulling from coollabsio/coolify-helper
Digest: sha256:4770886f7214920a14c97f408c0719b1f4a39c6839dbe0d152a33ca243ebea8b
Status: Image is up to date for ghcr.io/coollabsio/coolify-helper:latest
time="2024-04-17T17:20:07Z" level=warning msg="/data/coolify/source/docker-compose.yml: version is obsolete"
time="2024-04-17T17:20:07Z" level=warning msg="/data/coolify/source/docker-compose.prod.yml: version is obsolete"
 postgres Pulling 
 redis Pulling 
 soketi Pulling 
 coolify Pulling 
 coolify Error 
 postgres Error 
 redis Error 
 soketi Error 
Error response from daemon: toomanyrequests: retry-after: 317.096µs, allowed: 44000/minute

**Comment by andrasbacsai** [comment]
This has been already fixed.
