### ISSUE TITLE
[Bug]: Docker deployment not considering environment variables

### ISSUE THREAD

**Issue by vchiranjeeviakt** [coollabsio/coolify#2107]
### Description

I was using Dockerfile and Docker based deployment for one project. It worked properly as I expected when I first tried. Not exactly sure what happened, when I try the same thing after 2 days, it is failing health checks. I checked and it is failing to get the environment variables. Not sure what happened or if I m doing something. Please let me know if I m doing something wrong here. Quick response is appreciated. Thanks.

### Minimal Reproduction (if possible, example repository)

1. Add some environment variables in Coolify dashboard.
2. Use a Dockerfile to deploy an app which uses these environment variables.
3. Try to see if the deployment's health status becomes healthy and accesses the variables properly.

### Exception or Error

Health check of the deployment is failed.

### Version

v4.0.0-beta.271

**Comment by Maarcosv99** [comment]
I'm too.

**Comment by fcpauldiaz** [comment]
@vchiranjeeviakt could this be related to #2073 ? have you tried logging the env vars ?

**Comment by vchiranjeeviakt** [comment]
This is not about wrong health check @fcpauldiaz . Health check is working fine and failing because app is failing to start due to no environment variables. I tried to run the image created by coolify manually and it is throwing proper env not found error. I tried to echo a variable in pre-deployment command. From whatever I understood of pre-deployment command, it should print that value, correct me if I m wrong. But, didn't print anything in deployment logs.

Please confirm that adding env variables in dashboard should make them available for docker container right?

Also, I m using coolify cloud if that makes it any clear.

**Comment by fcpauldiaz** [comment]
@vchiranjeeviakt got it, I'm not a maintainer but in my experience when updating an env var, it is better to try a deploy without cache, maybe that could help.

**Comment by vchiranjeeviakt** [comment]
Yes @fcpauldiaz , I deployed without cache, I have deleted the environment and recreated new one as well. No luck. There is a version update, I will try again once.

**Comment by Christopher2K** [comment]
Hey, same situation here! 
Environment variables are not passed to the Dockerfile used by my Coolify resource. There's nothing in the doc related to this exact situation, everything seems to refer to the `docker-compose.yaml` deploy method

**Comment by SpuriousGer** [comment]
I am still having the same issue. Somehow, the environment variables are not being picked up. Maybe I am looking in the wrong spot, but I am running env in the Execute Command section to see the environment variables and there the ones from the project are not listed. But maybe they shouldn't be?

**Comment by Tahul** [comment]
Same issue here.

I entered every and all env variables properly for my preview deployments, and it fails to pass it towards the containers.

**Comment by andrasbacsai** [comment]
There are several issues mentioned in this, so let me answer them:

### Healthcheck fails on Dockerfile deployments
There was a change in the healthcheck process. Before it was always healthy, but since the previous few versions, it is checked properly.

This means you need to have `curl` or `wget` installed inside the Docker image, otherwise Coolify cannot check anything.

If this is not a solution for your use-case, turn off the healthcheck.

### Build env variables are not shown during build-time
Do not forget to add them as `ARG BUILDENV` in your Dockerfile. More details [here](https://docs.docker.com/reference/dockerfile/#arg).

### Pre commands
It has been fixed since then. It should work now.

**Comment by Tahul** [comment]
@andrasbacsai ; I'm not sure my issue is related.

I'm failing to pass preview env variables to a docker-compose project.

It works perfectly fine for raw env variables but never passes properly to preview ones.

I'm using Coolify Cloud and all the latest updates.

I've tried:
- Duplicated env variables in `args`, `environment` to ensure they are present
- Rebuilding all my containers, it always work properly in base deployment, never passes in preview
- Moving ARG in all steps of my image build
- Rewriting every env variables by hand instead of developer view
- Enabling/disabling "build variable" and all other settings and redeploying

**Comment by andrasbacsai** [comment]
Ah, preview deployments. I can reproduce that one - will fix it.

**Comment by Tahul** [comment]
Thank you so much for quick response @andrasbacsai ; loving Coolify here! :)

**Comment by knurzl** [comment]
Can we please reopen this issue? Im on beta 306 and i still (or maybe again) having the issue that in my preview build none of my preview or normal environment variables are considered.

**Comment by JeromeK13** [comment]
Can confirm same issue again with beta 306 also on my end. 
Also seeing strange behavior with $ signs in the env values

**Comment by jlat96** [comment]
I have the same issue as @knurzl on beta.306. I have several environment variables defined but my docker container is not able to access them. @andrasbacsai can we please re-open this issue?

**Comment by knurzl** [comment]
> Can confirm same issue again with beta 306 also on my end. Also seeing strange behavior with $ signs in the env values

The dollar sign is a special character to reference other variables. If you want to use it literal you have to check the box "is literal".

**Comment by JeromeK13** [comment]
> > Can confirm same issue again with beta 306 also on my end. Also seeing strange behavior with $ signs in the env values
> 
> 
> 
> The dollar sign is a special character to reference other variables. If you want to use it literal you have to check the box "is literal".

Yes indeed got everything working. please ignore my comment from above 👍

**Comment by diogotr7** [comment]
I'm running into this issue as well. A build-time environment variable works perfectly for regular deployments but seems to be missing during preview deployments. Using version beta 315.

**Comment by Cryszon** [comment]
I can't seem to get build variables to work with Compose.

I have these two files:

```yml
# docker-compose.yml
services:
  app:
    build:
      dockerfile: Dockerfile
```

```Dockerfile
# Dockerfile
FROM alpine:latest
ARG test_secret
RUN echo ${test_secret} > /test_secret_file
ENTRYPOINT ["tail", "-f", "/dev/null"]
```

I add `test_secret` variable in "Environment Variables" and check "Build Variable?".

Deployment results in `test_secret_file` being empty when using "Docker Compose" Build Pack, but with "Dockerfile" Build Pack, the file contains the value.

**Comment by a0m0rajab** [comment]
Same issue with beta.355

**Comment by duck4i** [comment]
Same issue with beta 360

**Comment by jycouet** [comment]
I'm in `v4.0.0-beta.373`, and inside the docker, I don't have my envs set. Only at the build time, not at runtime.

**Comment by twilwa** [comment]
to clarify -- does this issue indicate that when deploying via docker, env vars can't be set during build time? this essentially renders docker deployments unusable unless they have no env vars, correct? or is there a workaround?

**Comment by Cryszon** [comment]
> to clarify -- does this issue indicate that when deploying via docker, env vars can't be set during build time? this essentially renders docker deployments unusable unless they have no env vars, correct? or is there a workaround?

If you're using Docker Compose, I've written two articles based on my research and testing. Things might've changed since then, but this is what I currently use in production.

[Environment variables and build args for Docker Compose in Coolify](https://cryszon.github.io/posts/environment-variables-and-build-args-for-docker-compose-in-coolify/)

[Docker build secrets in Coolify](https://cryszon.github.io/posts/docker-build-secrets-in-coolify/)

_GH permalinks: [1](https://github.com/Cryszon/cryszon.github.io/blob/5edcd140618302a7ea839bcf0de2975a1be32d8b/src/content/posts/environment-variables-and-build-args-for-docker-compose-in-coolify.md), [2](https://github.com/Cryszon/cryszon.github.io/blob/5edcd140618302a7ea839bcf0de2975a1be32d8b/src/content/posts/docker-build-secrets-in-coolify.md)_

**Comment by lechnerio** [comment]
I also have this issue with v4.0.0-beta.380.

Did anyone find a workaround yet so far?

**Comment by jycouet** [comment]
In `v4.0.0-beta.380` (cloud), 
I was about to refresh the issue... BUT, I managed to make it working thx to the tips here:

![Image](https://github.com/user-attachments/assets/6be6e675-0edf-4ab4-a6b5-d63be7bba5ee)

So starting your `Dockerfile` with: 
```
ARG GITHUB_API_TOKEN
```
Will bring the GITHUB_API_TOKEN in.

**Comment by vojtech-cerveny** [comment]
This is still issue on `420.6` build. 

I have same docker-compose.yml for "production" and for preview application. I tried same build same branch in "production" and Preview application and production has no issue at all, but Preview application fails on build due to missing ENV.

I have same envs, all marked as `Build Variable`. 

I also tried to Nixpacks and preview application and it seems, that it is the same or similar problem - the env doesn't work properly. 

```yml
version: "3.8"

services:
  # PostgreSQL Database
  appDb:
    container_name: app-db-ci
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - app-db-data:/var/lib/postgresql/data

  prisma-migrate:
    build:
      context: .
      dockerfile: Dockerfile.migration
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@appDB:5432/${POSTGRES_DB}
    depends_on:
      appDb:
        condition: service_healthy
    restart: "no"

  # Next.js Application
  web:
    container_name: app-app-ci
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - prisma-migrate
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@appDb:5432/${POSTGRES_DB}
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PRISMA_CLI_BINARY_TARGETS=linux-musl-arm64-openssl-3.0.x
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    restart: "no"

volumes:
  app-db-data:
```

in application I check if app has one env - during building
```ts
import { z } from "zod";

const envSchema = z.object({
  DISCORD_WEBHOOK_URL: z.string(),
});

const env = envSchema.safeParse(process.env);

if (!env.success) {
  console.error("Invalid environment variables:", env.error);
  process.exit(1);
}

export default env.data;
```


and logs from coolify
```
#27 6.790    ▲ Next.js 15.3.4
#27 6.790
#27 6.873    Creating an optimized production build ...
#27 49.10  ✓ Compiled successfully in 37.0s
#27 49.11    Linting and checking validity of types ...
#27 49.42  ⨯ ESLint: Failed to load config "next/core-web-vitals" to extend from. Referenced from: /app/.eslintrc.json
#27 56.17    Collecting page data ...
#27 56.86 Invalid environment variables: Error [ZodError]: [
#27 56.86   {
#27 56.86     "code": "invalid_type",
#27 56.86     "expected": "string",
#27 56.86     "received": "undefined",
#27 56.86     "path": [
#27 56.86       "DISCORD_WEBHOOK_URL"
#27 56.86     ],
#27 56.86     "message": "Required"
#27 56.86   }
#27 56.86 ]
#27 56.86     at get error [as error] (.next/server/chunks/986.js:2:73159) 
```

**Comment by lilendian0x00** [comment]
This issue is killing me ;(

**Comment by lilendian0x00** [comment]
For anyone who wants to add env at build time to the docker compose, put your ENV at the ARG under the build section like this:

`- MY_ENV`

and then check it as "build time variable" in environment variable page.

**Comment by Arsh1a** [comment]
> For anyone who wants to add env at build time to the docker compose, put your ENV at the ARG under the build section like this:
> 
> `- MY_ENV`
> 
> and then check it as "build time variable" in environment variable page.

What about runtime? :(

**Comment by JanUlrichR** [comment]
This is also a problem when using absolute paths together with the env_file parameter like this in docker composes:
```
env_file:
      - /absolute/path/to/my/.env
```

**Comment by sheecegardezi** [comment]
This is crazy! There shouldn’t be so many workarounds or so much repetition of environment variables across different places. You define them once in the Docker Compose env section, then again as build arguments in the build section, and once more as ARG entries in the Dockerfile.

Defining an environment variable or secret once should be enough! Docker Compose has standard ways to handle environment variables, just support them properly. It should allow passing them directly into the Dockerfile, where they can be read and converted to environment variables automatically, without requiring manual duplication.

This shouldn’t be a case of “partial support” for Docker Compose. If I want to use a .env file, I can always copy and paste the variables manually into the environment settings or secrets in the developer view, while keeping credentials safely hidden from git history.

**Comment by andrasbacsai** [comment]
Closing old issue (which is probably fixed already). Reopen if still reproducible.
