### ISSUE TITLE
[Bug]: Predefined environment variables not passed to Nixpacks

### ISSUE THREAD

**Issue by sillvva** [coollabsio/coolify#2653]
### Description

I pushed a PR to test predefined environment variables to a preview deployment on my Sveltekit app. The environment variables are being passed to Nixpacks as literal strings rather than being replaced with the predefined values.

I followed the instructions here: https://coolify.io/docs/knowledge-base/environment-variables

### Minimal Reproduction (if possible, example repository)

Example variables:
```
TEST_URL=$COOLIFY_URL
PUBLIC_TEST_URL=$COOLIFY_URL
```
`Build variable` is checked. `Is Literal?` is not checked.

![image](https://github.com/coollabsio/coolify/assets/5138384/512736bb-077e-4691-af10-eba54fed84bb)

### Exception or Error

The resulting `Final Nixpacks plan` looks like this:
```
Final Nixpacks plan: {
"providers": [],
"buildImage": "ghcr.io\/railwayapp\/nixpacks:ubuntu-1716249803",
"variables": {
"SOURCE_COMMIT": "8887ff2d43fa705c29557d55a2320a50b95f36eb",
...HIDDEN_REAL_VARIABLES...
"PUBLIC_TEST_URL": "$COOLIFY_URL",
"TEST_URL": "$COOLIFY_URL",
"CI": "true",
"NIXPACKS_METADATA": "node",
"NODE_ENV": "production",
"NPM_CONFIG_PRODUCTION": "false"
},
```
And the resulting environment variables look like this with `console.table`:
```
#14 13.85 Coolify check: process.env
#14 13.85
#14 13.85 ┌─────────────────┬────────────────┐
#14 13.85 │ (index) │ Values │
#14 13.85 ├─────────────────┼────────────────┤
#14 13.85 │ PUBLIC_TEST_URL │ '$COOLIFY_URL' │
#14 13.85 │ TEST_URL │ '$COOLIFY_URL' │
#14 13.85 └─────────────────┴────────────────┘
```

### Version

v4.0.0-beta.297

**Comment by Aunali321** [comment]
i thought i was going crazy

**Comment by jacobschwantes** [comment]
Also facing this issue. The environment variable is getting set correctly in the container but ```$coolify_url``` is what gets passed if its marked as a build variable.

**Comment by lorenzomigliorero** [comment]
Probably related to https://github.com/coollabsio/coolify/issues/2316

**Comment by BedroomDev** [comment]
Still have the issue in [v4.0.0-beta.335](https://github.com/coollabsio/coolify/releases/tag/v4.0.0-beta.335)

**Comment by jycouet** [comment]
I think that this is fixed (I'm on v4.0.0-beta.373)

**Comment by sillvva** [comment]
I am still having this issue on 4.0.0-beta.373

Example environment variable (build variable checked, literal not checked):
```
PUBLIC_TEST_URL=$COOLIFY_URL
```
![Image](https://github.com/user-attachments/assets/ec9086d7-a2d4-4677-93f4-690cb2d34f55)

Logged output during build:
```
#14 14.79 │ PUBLIC_TEST_URL       │ '$COOLIFY_URL'
```

**Comment by 99Arrzel** [comment]
Is there any workaround for this at the moment?
This is annoying for PR deployments lol

**Comment by BedroomDev** [comment]
still doesnt work on 4.0.0-beta.380 newest version to date

 - UndefinedVar: Usage of undefined variable '$NIXPACKS_PATH' (line 18)
2025-Jan-15 14:55:41.022784

**Comment by sillvva** [comment]
I think I saw a potential fix coming in 381. It's not released yet.

I noticed it at about 0:04 on the video
https://bsky.app/profile/heyandras.dev/post/3lfp73cifx62e

**Comment by viktorkuts** [comment]
> I think I saw a potential fix coming in 381. It's not released yet.
> 
> I noticed it at about 0:04 on the video https://bsky.app/profile/heyandras.dev/post/3lfp73cifx62e

Nope, I tried 381 and even 382 and that didn't fix any issues, still ongoing

**Comment by viktorkuts** [comment]
Adding to this, it seems as if it is only limited to static pages, like using Vite, Svelte etc.
Whenever I dump the process env in my frontend (Vite & React) static build, I get no COOLIFY_ or they stay literals as $COOLIFY_
However in my backend (Java Spring Boot), the env dump has all the predefined variables, without even needing to bind them to a project variable.

One thing to note however, when I dump the envs in the terminal of the frontend in coolify, I do see the predefined variables, which is more how the backend deployment behaves. It's very strange behavior.

**Comment by andrasbacsai** [comment]
I figured out a good way to fix this. So it is coming into the next version v408.
