### ISSUE TITLE
[Bug]: projects list not opening

### ISSUE THREAD

**Issue by tuliofaria** [coollabsio/coolify#2657]
### Description

On latest version, the project listing is not working.
![image](https://github.com/coollabsio/coolify/assets/103433/078993c5-1c43-4717-acfb-a8687da80d9f)

### Minimal Reproduction (if possible, example repository)

- Having some already running projects
- Go to project listing

### Exception or Error

![image](https://github.com/coollabsio/coolify/assets/103433/31fb081c-8d1b-47be-861d-8f4072a58486)

### Version

v4.0.0-beta.299

**Comment by matteo-sku** [comment]
Same issue here
<img width="1156" alt="Screenshot 2024-06-24 at 10 20 45 AM" src="https://github.com/coollabsio/coolify/assets/101604815/a5b0f85b-5f68-4508-95b3-e059663a35a2">

**Comment by matteo-sku** [comment]
Just fixed it - Upgrade to v4.0.0-beta.300 @tuliofaria

**Comment by andrasbacsai** [comment]
Yes. It is fixed in v299+.

**Comment by tuliofaria** [comment]
Hey @andrasbacsai and @matteo-sku . Hum... I updated to [v4.0.0-beta.300](https://github.com/coollabsio/coolify/releases/tag/v4.0.0-beta.300) - and it still happening.

**Comment by andrasbacsai** [comment]
let me check

**Comment by andrasbacsai** [comment]
> Same issue here <img alt="Screenshot 2024-06-24 at 10 20 45 AM" width="1156" src="https://private-user-images.githubusercontent.com/101604815/342374830-a5b0f85b-5f68-4508-95b3-e059663a35a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNDYyNjgsIm5iZiI6MTcxOTI0NTk2OCwicGF0aCI6Ii8xMDE2MDQ4MTUvMzQyMzc0ODMwLWE1YjBmODViLTVmNjgtNDUwOC05NWIzLWUwNTk2NjNhMzVhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQxNjE5MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMDllZWU3MDQ4YzI5OWEyNDdkYjU5YjY5YWJmYzJjMGM0MjVhZDM1NGRjY2Y4OTM0NmMxYTlkYmQ0OGY2Mzg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tNpmrhr3Lk69DdjZZ_GG0jl3acM6Yj6IZt9--3PL1xs">

Is this happening to you @tuliofaria ?

**Comment by arthurbrunot** [comment]
Hi @andrasbacsai got the same error on a pretty new instance running on v297 that was working well. Upgrading to v298, v299, v300 throws this (@tuliofaria error i guess ) :
![Capture d’écran 2024-06-24 à 18 35 25](https://github.com/coollabsio/coolify/assets/47625753/937e33cc-03fa-4e4c-aede-41a73c3d5b18)

**Comment by andrasbacsai** [comment]
It is fixed in v301 (releasing soon).

**Comment by arthurbrunot** [comment]
In addition, i got the exact same error on v300 (on project and dashboard page)

**Comment by andrasbacsai** [comment]
Released. Let me know if you still have this error.

**Comment by tuliofaria** [comment]
Hey @andrasbacsai , great stuff. Now it's fixed 🥳   Thank you so much.
