### ISSUE TITLE
[Bug]: Build server + Git, latest image not pulled

### ISSUE THREAD

**Issue by ruohki** [coollabsio/coolify#3537]
### Error Message and Logs

I am trying to use a static site generator that grabs its content from a remote source. By doing so, even if I trigger a build, the latest image is not pulled to the target server.

Coolify tags the images with the latest commit, but in this specific case the commit and thus the tag does not change as the repo stays the same. A new image is built and pushed to the registry, however Coolify won't pull the image properly as the tag has not changed.

https://github.com/coollabsio/coolify/blob/e42c7e258cd93ee31a8b2788a87a139860befc2c/app/Jobs/ApplicationDeploymentJob.php#L2275

This should be preceded by a `docker compose pull` so that the latest image, even if the tag won't change, gets pulled.

### Steps to Reproduce

1. Set up a deployment of a git repo with a build server with a static site generator of choice that pulls in remote content
2. Deploy without changes in the repo.

### Coolify Version

v4.0.0-beta.341

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04

**Comment by valentinschabschneider** [comment]
Yeah I encountered the same issue. I fixed this by typing `docker compose pull` as the build command.

**Comment by ruohki** [comment]
The thing is i dont use compose. I use simple Dockerfile. But coolify generates and deploys a compose project

**Comment by billythedummy** [comment]
I just wasted an entire afternoon because of this bug. Kept wondering why something I thought I fixed kept popping up on my coolify preview deploy. Finally decided to ssh into the server and saw that the docker image digest didnt match the latest one pushed by the build server to the registry at all.

Please fix this asap, it's probably exactly how @ruohki described it. Preview deploys are a pita for build-pack=Dockerfile if we have to ssh into the server and delete the old image every time

**Comment by Patrick3131** [comment]
I am on #5194, but I am experiencing the same issue. I am building my images on Github. If I try to redeploy, Coolify isn't pulling my latest images. Anyone else are still experiencing the same issue?

**Comment by lucienbl** [comment]
Hey @Patrick3131 
I am building using a build server, and I use the GitHub container registry. I previously had the issue where updated preview build weren't pulled because of the same tag (pr-[#]). I opened a PR which force pull the latest image on preview builds by ignoring the tag which successfully resolved the issue for me. What do you mean when you say that you use GitHub to build your images ?

**Comment by Patrick3131** [comment]
It might be a slightly different issue, but connected to what you experienced.

I am building my docker images with a GitHub action, the GitHub action pushes it to the container registry. 

The format is:
ghcr.io/patrick3131/image:staging

So now when I am deploying with docker compose on Coolify and there was a previous deployment, it never pulls the new images.

Or is my process wrong? 

Also, I haven't found a work around. I tried to use `docker compose build --pull` as a custom build command but then I get this issue:

```
2025-Feb-28 08:58:01.192599
[CMD]: docker exec e8k44k8c0ckw44c8sgcgc04w bash -c 'cd /artifacts/e8k44k8c0ckw44c8sgcgc04w && docker compose --project-directory /artifacts/e8k44k8c0ckw44c8sgcgc04w build --pull'
2025-Feb-28 08:58:01.192599
no configuration file provided: not found
```

**Comment by lucienbl** [comment]
Hey @Patrick3131 

I see, I think it's the same issue. Your tag "staging" isn't changing across builds so after a first build, subsequent deployments ignore the new built image and keep the already pulled image that comes from a previous deployment as the tag didn't change.

My PR (#4771) only fixes the issue when using a build server, which isn't your case if I understand right. Maybe we should add the `--pull always` flag also on [this line](https://github.com/lucienbl/coolify/blob/a139cf154d2480d9c2fdb793d971ddfd283b67d6/app/Jobs/ApplicationDeploymentJob.php#L2277)  ?

Maybe a maintainer has a thought on this ?

**Comment by Patrick3131** [comment]
Thanks, sounds reasonable to me. Are you going to create a PR, or should I?

As a temporary fix, docker compose build --pull as a custom build command works.

**Comment by lucienbl** [comment]
I just made the change on my branch, however I couldn't test it right now. Feel free to take it and open a PR if you want !
https://github.com/lucienbl/coolify/commit/5de9f61f637d69360ee50550d552df00e762276b

**Comment by qumberrizvi** [comment]
Would love to see this merged. Since the problem continues to exist.

**Comment by qumberrizvi** [comment]
For future reference, the proposed solution in the related PR (for docker compose):

> ... if you are using a compose that is using an externally built image, you need to just add 
> ```yaml
> services:
>   service:
>     image: xxx
>     pull_policy: always
> ```
> this fixes issue of not always pulling your newly built image

**Comment by ruohki** [comment]
> For future reference, the proposed solution in the related PR (for docker compose):
> 
> > ... if you are using a compose that is using an externally built image, you need to just add
> > services:
> >   service:
> >     image: xxx
> >     pull_policy: always
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > this fixes issue of not always pulling your newly built image

This wont help if you do a Dockerfile deployment

**Comment by andrasbacsai** [comment]
This has been already fixed.
