### ISSUE TITLE
[Bug]: add `autocomplete="off"` (and `autofocus`) to "Search for name, fqdn…" search input in Projects

### ISSUE THREAD

**Issue by ksaitor** [coollabsio/coolify#3640]
### Error Message and Logs

Search field gets auto-filled with email in Chrome. 
Once you try to to click on one of your apps, search gets triggered and all your apps dissapear (since none of them match an auto-filled value). This requires a user to clear the input field every time they use Coolify

<img width="504" alt="Screenshot 2024-09-30 at 12 11 06" src="https://github.com/user-attachments/assets/47c253d2-d53a-4a3c-9190-9579ddcbe659">

Once you click on any project (without clearing the Search field), search gets triggered and all projects disappear: 

<img width="713" alt="Screenshot 2024-09-30 at 12 15 24" src="https://github.com/user-attachments/assets/0d66dac8-5a7a-4248-978b-c3756022a4db">

### Steps to Reproduce

1. Go to a project
2. For some users your search input will get autofiled with e.g. email
3. Once you try and click on a project, the search gets triggered and all projects dissapear

### Coolify Version

v4.0.0-beta.345

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu

**Comment by andrasbacsai** [comment]
It has been fixed in the latest version. Can you please upgrade and test it again?

**Comment by ksaitor** [comment]
> It has been fixed in the latest version. Can you please upgrade and test it again?

Just updated to  `v4.0.0-beta.347` - same issue :/

**Comment by ksaitor** [comment]
spent some time googling… Chrome disregards `autocomplete="off"`

best thread i found on this: https://stackoverflow.com/questions/15738259/disabling-chrome-autofill

some suggest `autocomplete="false"` instead of `autocomplete="off"`
or to `autocomplete="new-password"`

ps.
thanks for looking into this! seems like a small bug - but it's super annoying :(

**Comment by djsisson** [comment]
i think the issue is just a lack of a valid name attribute, since it wouldn't get autofilled with email if it was named something else entirely, same when deleting

**Comment by moshetanzer** [comment]
please fix this, evreytime i click any card/project it treats as some sort of submit and adds email to search bar - which means i have to click on a project, clear email go again and click on project @andrasbacsai - this is a massive issue

**Comment by ksaitor** [comment]
it's really bad. my current workaround is to run Tampermonkey chrome plugin with a script that removes the search field altogeather

```js
(function() {
    'use strict';
    document.querySelectorAll('input[name="null"]').forEach(input => input.remove());

    // Your code here...
})();
```

imho, if the Resources page does not have pagination, it's best to remove the search field altogether. People know how to use Command+F to search on page…

**Comment by andrasbacsai** [comment]
I released a fix that set autocomplete to off, and removes autofocus. Can you please check with v349?

**Comment by nofalx** [comment]
Hi @andrasbacsai 

I tested with `v4.0.0-beta.349` and chrome `Version 128.0.6613.137 (Official Build) (64-bit)` and the issue is still there, with the new release the field gets prefilled but doesnt filter until you click anywhere on the page which is super confusing.

It is sad how the chrome decided to not respect `autocomplete=off`.

Based on my previous experience if you have 1 field with `type="password"` in page then it will treat some of the fields as username field by force. The easiest way to fix it is to wrap the password fields by `<form>` element.

From what I see this is what causing the bug
![image](https://github.com/user-attachments/assets/aa9d4de3-0a8f-497e-ae2f-37b33475662e)

wrap this div and any other div with something like `<form onsubmit="return false">` and it could be fixed

**Comment by andrasbacsai** [comment]
> Hi @andrasbacsai 
> 
> 
> 
> I tested with `v4.0.0-beta.349` and chrome `Version 128.0.6613.137 (Official Build) (64-bit)` and the issue is still there, with the new release the field gets prefilled but doesnt filter until you click anywhere on the page which is super confusing.
> 
> 
> 
> It is sad how the chrome decided to not respect `autocomplete=off`.
> 
> 
> 
> Based on my previous experience if you have 1 field with `type="password"` in page then it will treat some of the fields as username field by force. The easiest way to fix it is to wrap the password fields by `<form>` element.
> 
> 
> 
> From what I see this is what causing the bug
> 
> ![image](https://github.com/user-attachments/assets/aa9d4de3-0a8f-497e-ae2f-37b33475662e)
> 
> 
> 
> wrap this div and any other div with something like `<form onsubmit="return false">` and it could be fixed  
> 
> 

Thanks for the investigation. I will try to fix it (again and again, until it will work).

The one thing I do not understand is that why it came up now. I did not change anything that is related to this. 🤔

**Comment by djsisson** [comment]
the enter password to delete project was added

**Comment by sisou** [comment]
Inputs should always be wrapped in a `<form>`, so you can use the `onsubmit` handler when the user presses the ENTER key.

**Comment by andrasbacsai** [comment]
> Hi @andrasbacsai
> 
> I tested with `v4.0.0-beta.349` and chrome `Version 128.0.6613.137 (Official Build) (64-bit)` and the issue is still there, with the new release the field gets prefilled but doesnt filter until you click anywhere on the page which is super confusing.
> 
> It is sad how the chrome decided to not respect `autocomplete=off`.
> 
> Based on my previous experience if you have 1 field with `type="password"` in page then it will treat some of the fields as username field by force. The easiest way to fix it is to wrap the password fields by `<form>` element.
> 
> From what I see this is what causing the bug ![image](https://private-user-images.githubusercontent.com/42375159/372814996-aa9d4de3-0a8f-497e-ae2f-37b33475662e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NzkzMDgsIm5iZiI6MTcyNzg3OTAwOCwicGF0aCI6Ii80MjM3NTE1OS8zNzI4MTQ5OTYtYWE5ZDRkZTMtMGE4Zi00OTdlLWFlMmYtMzdiMzM0NzU2NjJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDE0MjMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiZjY1YTkzMmYxNjEzNDBiNzFlYjRiZjA2ZmMwNGY3YTA0NDIwYjA5ZTc2ZGEyYTUxZjlmZDg4NTg5ZDZhZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2vEUMxQu7gbL_c33fCj2UrH-qWMtxy0_12bYX9f9F2c)
> 
> wrap this div and any other div with something like `<form onsubmit="return false">` and it could be fixed

This breaks a lot of things. :(

So I am still open for suggestions.

**Comment by andrasbacsai** [comment]
Found the issue. It is in [this](https://github.com/coollabsio/coolify/blob/main/resources/views/components/modal-confirmation.blade.php) file, if it is not there, everything works.

**Comment by sisou** [comment]
Yes, it's the password input at https://github.com/coollabsio/coolify/blob/main/resources/views/components/modal-confirmation.blade.php#L275

That makes Chrome take any preceding input as the username field.

Wrapping either of those fields (best the password field) into its own `<form>`, prevents chrome from autofilling both.

**Comment by andrasbacsai** [comment]
This one is causing it (wtf):

![image](https://github.com/user-attachments/assets/754b3f57-fa4c-41d6-8784-ebbd639f70c4)

**Comment by djsisson** [comment]
just remove that step :D

**Comment by andrasbacsai** [comment]
> Yes, it's the password input at https://github.com/coollabsio/coolify/blob/main/resources/views/components/modal-confirmation.blade.php#L275
> 
> That makes Chrome take any preceding input as the username field.
> 
> Wrapping either of those fields (best the password field) into its own `<form>`, prevents chrome from autofilling both.

Yes, wrapping it in `<form action="return false">` fixes the issue. wtf #2

I will start making games with Godot. okthxbye

**Comment by ksaitor** [comment]
✅ nice! it worked! can confirm ✅
