### ISSUE TITLE
[Bug]: Traefik possibly not forwarding real IP

### ISSUE THREAD

**Issue by stevetoza** [coollabsio/coolify#438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Unable to access apps using coolify if they're IP restricted this was working fine before the switch from HA Proxy

### Steps To Reproduce

Have an app that is restricted via IP > App > Secrets > ALLOWED_IP_ADDRESSES
Try accessing the app after the upgrade to Traefik
The app is not accessible getting 403 access denied 
Could this be Traefik not forwarding the IP to the application correctly

### Version

2.9.1

**Comment by andrasbacsai** [comment]
I released a fix, and now it should forward IP addresses.

**Comment by stevetoza** [comment]
Hey, yep looks all good now, thanks for fixing so quick 👍

**Comment by stevetoza** [comment]
Edit to the above, my browser cached the page, looks like im still getting a 403 access denied
