### ISSUE TITLE
[Bug]: Docker Compose Deployments Still Have Issues If Repo Files Are Needed.

### ISSUE THREAD

**Issue by DanyaalMajid** [coollabsio/coolify#5182]
## Description

We are encountering issues with Docker Compose deployments when repository files are required, similar to past issues referenced below. 

The **Dockerfile** and **docker-compose.yml** are located in the `docker/` directory in the repository. They are properly detected in the dashboard, but deployment fails with an error stating that the `/artifacts/docker` directory does not exist.

## Related Issues  
- https://github.com/coollabsio/coolify/issues/1996  
- https://github.com/coollabsio/coolify/issues/3114  

These issues seem related, but our case appears to be a new variation of the problem.

## Build Log  
```
Starting deployment of danyaal-majid/replica-backend:main to localhost.
Preparing container with helper image: ghcr.io/coollabsio/coolify-helper:1.0.6.
[CMD]: docker rm -f z0808gscooo8coc8o008ks08
Error response from daemon: No such container: z0808gscooo8coc8o008ks08
[CMD]: docker run -d --network coolify --name z0808gscooo8coc8o008ks08 --rm -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/coollabsio/coolify-helper:1.0.6
7de73f56514fdea3ad93ed41d11de4d58f98e526dafb870ed47d80fc45d6aa9f
[CMD]: docker exec z0808gscooo8coc8o008ks08 bash -c 'GIT_SSH_COMMAND="ssh -o ConnectTimeout=30 -p 22 -o Port=22 -o LogLevel=ERROR -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" git ls-remote [https://x-access-token:<REDACTED>@github.com/DanyaalMajid/replica-backend.git](https://x-access-token:%3CREDACTED%3E@github.com/DanyaalMajid/replica-backend.git) main'
76aa2432285ef42460f8f898cadab0c4e109abed	refs/heads/main
9495055499d8b523b47138781da4a292870fee0f	refs/remotes/origin/main
----------------------------------------
Importing DanyaalMajid/replica-backend:main (commit sha HEAD) to /artifacts/z0808gscooo8coc8o008ks08.
[CMD]: docker exec z0808gscooo8coc8o008ks08 bash -c 'git clone -b "main" [https://x-access-token:<REDACTED>@github.com/DanyaalMajid/replica-backend.git](https://x-access-token:%3CREDACTED%3E@github.com/DanyaalMajid/replica-backend.git) /artifacts/z0808gscooo8coc8o008ks08 && cd /artifacts/z0808gscooo8coc8o008ks08 && GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" git submodule update --init --recursive && cd /artifacts/z0808gscooo8coc8o008ks08 && GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" git lfs pull'
Cloning into '/artifacts/z0808gscooo8coc8o008ks08'...
[CMD]: docker exec z0808gscooo8coc8o008ks08 bash -c 'cd /artifacts/z0808gscooo8coc8o008ks08 && git log -1 76aa2432285ef42460f8f898cadab0c4e109abed --pretty=%B'
Add docker configurations.
[CMD]: docker exec z0808gscooo8coc8o008ks08 bash -c 'stat -c '%F' /artifacts/z0808gscooo8coc8o008ks08.'
stat: can't stat '/artifacts/z0808gscooo8coc8o008ks08.': No such file or directory
Pulling & building required images.
[CMD]: docker exec z0808gscooo8coc8o008ks08 bash -c 'SOURCE_COMMIT=76aa2432285ef42460f8f898cadab0c4e109abed COOLIFY_BRANCH=main  docker compose --env-file /artifacts/z0808gscooo8coc8o008ks08/.env --project-name s0s00o8440gwsoososo0o4gk --project-directory /artifacts/z0808gscooo8coc8o008ks08 -f /artifacts/z0808gscooo8coc8o008ks08/docker/docker-compose.yml build --pull'
Service celery  Building
Service fastapi  Building
resolve : lstat /artifacts/docker: no such file or directory
Oops something is not okay, are you okay? 😢
Service celery  Building
Service fastapi  Building
resolve : lstat /artifacts/docker: no such file or directory
```

### Steps to Reproduce

1. **Set up a repository** with a `Dockerfile` and `docker-compose.yml` **inside a subdirectory** (e.g., `docker/`).
2. **Connect the repository** to Coolify and ensure it detects the Docker Compose setup.
3. **Enable the "Preserve Repository During Deployment" Option**.
4. **Trigger a deployment** using the Coolify dashboard.
5. **Observe the build log**, which should show errors related to missing `/artifacts/docker` directory.
6. The deployment fails with the error:    
```
   resolve : lstat /artifacts/docker: no such file or directory
```

This issue seems related to previous problems with handling repository files in deployments.

### Coolify Version

v4.0.0-beta.394

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.10

**Comment by nuxwin** [comment]
@andrasbacsai For the record, the issue is caused by word wrapping. Disabling it resolves the problem:

File: /var/www/html/resources/views/components/form/monaco-editor.blade.php:
```
...
wordWrap: 'off'
...
```

Of course, disabling word wrapping is not the proper solution. I believe there's a bug elsewhere, but this serves as a temporary workaround.

**Comment by nuxwin** [comment]
@andrasbacsai Sorry, the comment below was not for this issue ...

**Comment by MarArMar** [comment]
Putting the same exact docker compose file at the root of the repo (and putting context : . ) solved the problem 👍

**Comment by DanyaalMajid** [comment]
I stumbled on the same thing, but there were issues in my compose file, so I though that may have been the problem.

Basically docker compose files in sub directories cause breakage of builds, Docker files themselves can be kept in sub directories. But the compose file must be in the root always.

**Comment by sglbl** [comment]
Is there any update on this issue so that we can still be able to use docker compose files in `docker/` folder

**Comment by sglbl** [comment]
> I stumbled on the same thing, but there were issues in my compose file, so I though that may have been the problem.
> 
> Basically docker compose files in sub directories cause breakage of builds, Docker files themselves can be kept in sub directories. But the compose file must be in the root always.

Actually when I tried with these settings, it worked for me.
My `docker`/ directory:

![Image](https://github.com/user-attachments/assets/29bdeda9-f3a9-43d1-baec-eae3341d1df9)

My Coolify Setting:

![Image](https://github.com/user-attachments/assets/18dc1fff-914c-4df9-ac33-cef17a8d7d83)

So even though my base directory is root, on coolify I had to select docker/ but then it worked.

**Comment by DanyaalMajid** [comment]
It may have been fixed, i haven't messed with my deployment system for a couple months, will have to try again and see if its fixed.

**Comment by djedu28** [comment]
> > I stumbled on the same thing, but there were issues in my compose file, so I though that may have been the problem.
> > Basically docker compose files in sub directories cause breakage of builds, Docker files themselves can be kept in sub directories. But the compose file must be in the root always.
> 
> Actually when I tried with these settings, it worked for me. My `docker`/ directory:
> 
> img 
> 
> My Coolify Setting:
> 
> img 
> 
> So even though my base directory is root, on coolify I had to select docker/ but then it worked.

God bless you! I was suffering from this bug for days. Unfortunately the bug is still active.

<img width="919" height="642" alt="Image" src="https://github.com/user-attachments/assets/2984d7f3-777b-4b93-bb4c-c1187119c9ff" />

And luckily your solution works with nested directories

**Comment by sglbl** [comment]
@djedu28 You're welcome! I'm glad this solved your issue.

**Comment by djedu28** [comment]
Bug persists in current LTS version v4.0.0

**Comment by djsisson** [comment]
coolify sets the compose project directory to be the root of the repo instead of the location of the compose file (coolify should not set this at all, as compose will use the correct project dir from the passed in file location)

when setting the build context, compose takes the project directory and build context to generate the path to pass to buildkit, so when using a path with any kind of traversal backwards, will take the context outside of the repo

yes its a bug, its possible to override the context using a flag to bake, but im not sure you can use that in a custom build command

tldr
--project-directory should be removed or set to compose location
https://github.com/coollabsio/coolify/blob/49656aa1edbe8aa6f7f7077dbf689cb1a08f05ee/app/Jobs/ApplicationDeploymentJob.php#L761-L763
as well as when using custom commands

the only time its needed is when youre using compose overrides, modifying the compose from outside of the repo or using stdin, you would then need to point back to the initial compose location to correctly resolve context location
