### ISSUE TITLE
[Bug]: Incorrect link to Framework Specific Docs

### ISSUE THREAD

**Issue by kevincam3** [coollabsio/coolify#5346]
### Error Message and Logs

When configuring a project there's a "Build" section and in that section there's a link to "Framework Specific Docs" it's missing the trailing "/" so it doesn't go to the correct page.

![Image](https://github.com/user-attachments/assets/b1c60fb8-abf8-481f-9e11-cbae940d28b7)

### Steps to Reproduce

1.
2.
3.
4.

### Coolify Version

v4.0.0-beta.398

### Are you using Coolify Cloud?

Yes (Coolify Cloud)

**Comment by ShadowArcanist** [comment]
Hi @kevincam3, thanks for reporting this issue! 

The problem has now been resolved with this PR: https://github.com/coollabsio/documentation-coolify/pull/180. 

Please check and let us know if everything is working as expected.

**Comment by andrasbacsai** [comment]
I add a temporary fix in this repo, until we figure out the trailing slash problem with the docs. 

(https://github.com/coollabsio/documentation-coolify/pull/180 did not fix the issue.)
