### ISSUE TITLE
[Bug]: Nixpacks fails with vite: not found route

### ISSUE THREAD

**Issue by JSanchezFDZ** [coollabsio/coolify#5499]
### Error Message and Logs

The display of my Vite project is correct, even if I open the default route it works, but when navigating between routes I can see the error: 404.
The project works correctly, even if I test it in other tools like Vercel, the operation is correct.
**I think it was working correctly in 398**

**Error message in browser:**
404 Not Found
nginx/1.27.4

**Logs**
```
2025/04/01 10:46:13 [error] 29#29: *1 open() "/usr/share/nginx/html/404.html" failed (2: No such file or directory), client: ******, server: , request: "GET /login HTTP/1.1", host: "dev.******.com", referrer: "https://dev.******.com/"
2025/04/01 10:46:14 [error] 29#29: *1 open() "/usr/share/nginx/html/404.html" failed (2: No such file or directory), client: ******, server: , request: "GET /login HTTP/1.1", host: "dev.******.com", referrer: "https://dev.******.com/"
2025/04/01 10:46:15 [error] 29#29: *1 open() "/usr/share/nginx/html/404.html" failed (2: No such file or directory), client:******, server: , request: "GET /login HTTP/1.1", host: "dev.******.com", referrer: "https://dev.******.com/"
2025/04/01 10:46:17 [error] 29#29: *1 open() "/usr/share/nginx/html/404.html" failed (2: No such file or directory), client: ******, server: , request: "GET /login HTTP/1.1", host: "dev.******.com", referrer: "https://dev.******.com/"
2025/04/01 10:46:18 [error] 29#29: *1 open() "/usr/share/nginx/html/404.html" failed (2: No such file or directory), client: ******, server: , request: "GET /login HTTP/1.1", host: "dev.******.com", referrer: "https://dev.******.com/"
2025/04/01 10:46:18 [error] 29#29: *1 open() "/usr/share/nginx/html/404.html" failed (2: No such file or directory), client: ******, server: , request: "GET /login HTTP/1.1", host: "dev.******.com", referrer: "https://dev.******.com/"
```

### Steps to Reproduce

1. Deploy Vite project with routes
2. Try to visit routes

### Coolify Version

v4.0.0-beta.400

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04.1 LTS

### Additional Information

It also happens with React projects.
Previously it was working.

**Comment by djsisson** [comment]
@JSanchezFDZ this was just fixed in v402

**Comment by JSanchezFDZ** [comment]
@djsisson hello! Thank you for your quick response!

I just upgraded to 402 manually but I'm still getting the same error. I have tried to make a new deploy without cache.

Should I delete the project and create it again?

**Comment by djsisson** [comment]
@JSanchezFDZ make sure the is spa option is also ticked

**Comment by JSanchezFDZ** [comment]
@djsisson true, its working!
Thank you so much!

Perhaps this option should be activated automatically when it detects that it is a Vite/React project...

**Comment by peaklabs-dev** [comment]
This issue has been fixed in the latest version.
