### ISSUE TITLE
[Bug]: Incorrect Environment Variables in Convex Deployment Template

### ISSUE THREAD

**Issue by TotalLag** [coollabsio/coolify#5569]
### Error Message and Logs

**Description:**

The current Convex deployment template in Coolify sets incorrect environment variables for `CONVEX_CLOUD_ORIGIN` and `CONVEX_SITE_ORIGIN` in the `backend` service definition. These variables should point to the backend service's Fully Qualified Domain Name (FQDN), but they are currently pointing to the dashboard's FQDN (`SERVICE_FQDN_CONVEX_6791`). Additionally, the `CONVEX_SITE_ORIGIN` has an optional `/http` suffix in the original template.

This causes issues because the backend relies on these origins for proper operation, and the dashboard needs to communicate with the backend using its correct address.

**Original Incorrect Configuration:**

In the `backend` service definition:
```yaml
    environment:
      # ... other variables
      - 'CONVEX_CLOUD_ORIGIN=${SERVICE_FQDN_CONVEX_6791}'
      - 'CONVEX_SITE_ORIGIN=${SERVICE_FQDN_CONVEX_6791}/http'
      # ... other variables
```

**Proposed Fix:**

The environment variables should be updated to use the backend's FQDN variable (SERVICE_FQDN_BACKEND_3210) and remove the /http suffix from CONVEX_SITE_ORIGIN:
```yaml
    environment:
      # ... other variables
      - 'CONVEX_CLOUD_ORIGIN=${SERVICE_FQDN_BACKEND_3210}'
      - 'CONVEX_SITE_ORIGIN=${SERVICE_FQDN_BACKEND_3210}'
      # ... other variables
```
**Impact:**

Without this fix, self-hosted Convex deployments using this template may not function correctly, as internal services might try to communicate using the wrong origins or malformed URLs. In particular, users will results in a `404` missing page error if trying to upload files via dashboard or api.

Thank you for maintaining Coolify!

### Steps to Reproduce

1. Deploy template as-is
2. Visit the Dashboard --> Files
3. Try uploading a file
4. 404 failure

### Coolify Version

v4.0.0-beta.395

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04

**Comment by Cinzya** [comment]
@BradPerbs There is no ETA at the moment. This also has probably lower priority since there is a wrokaround for this bug.
If you click on `Edit Compose File` in Coolify you can apply the fix mentioned above to your running service.

**Comment by NarendraPatwardhan** [comment]
The workaround doesn't work either. I have been grappling with convex auth multiple times and the (non-coolify) dockerfile works but the convex instance that gets spun up through coolify always errors out during auth.

**Comment by saitobp** [comment]
> The workaround doesn't work either. I have been grappling with convex auth multiple times and the (non-coolify) dockerfile works but the convex instance that gets spun up through coolify always errors out during auth.

Can you share what non-coolify dockerfile are you using and how to configure it on coolify? I'm trying to use convex auth but without any success, I guess it's related to this issue, but if there's a alternative while the PR is not merged I would appreciate

Edit: I've tried the docker-compose from the self host docs on the convex github but I did not manage to get it working

**Comment by NarendraPatwardhan** [comment]
@saitobp If you are on convex discord I have shared my files there, they are searchable.

**Comment by Karnak19** [comment]
I've catched another bug, maybe it is linked to my poor knowledge of Coolify, I don't know but here it is:

The `SERVICE_FQDN_CONVEX` and `SERVICE_FQDN_CONVEX_6791` won't change and I can't update them manually, they are stuck on the `sslip.io` domain. 
You would say this might not be a big deal because it is working with my domains even with these env vars wrong, but the issue is when I call [`ctx.storage.generateUploadUrl()`](https://docs.convex.dev/file-storage/upload-files), it is generating an URL with the `sslip` domain

![Image](https://github.com/user-attachments/assets/d088cd20-d431-4f0b-9517-2f65117c66cb)

![Image](https://github.com/user-attachments/assets/3330fae5-7350-4400-a547-9184ed6745a3)

![Image](https://github.com/user-attachments/assets/06796af2-5643-4296-b15b-ef20643b7fa1)

**Comment by BradPerbs** [comment]
@Cinzya Indeed the workaround do not work, seems like coolify re-apply the original configuration automatically forcing it. As already mentioned by someone else as well.

**Comment by Cinzya** [comment]
Convex has been fixed in the upcoming version [v4.0.0-beta.419](https://github.com/coollabsio/coolify/pull/5815).
It's just still in internal testing and hasn't been rolled out the public yet.

**Comment by Karnak19** [comment]
After testing it (from `next` branch), the backend container won't start

```
2025-06-04T09:30:06.403349320Z Error: Origin url should start with https:// or http:// but got 'convex-g4os4o4ggkgco4owgcc4g8ck.152.53.17.218.sslip.io
```

It seems the change to `SERVICE_URL_CONVEX_3210|3211` introduced it. When changing it back to `SERVICE_FQDN_` the container starts correctly

**Comment by Karnak19** [comment]
(sorry for double comments, I couldn't add screenshots while editing the previous)


But still, the bug I mentioned still exists, even worse, the deployment url is now back to the fqdn url.


Previous template:
Deployment URL ✅ 
HTTP actions URL ❌

![Image](https://github.com/user-attachments/assets/ca7b0175-9d56-4fe7-8f59-1dff2ad26e4f)
 

Next template:
- Deployment URL ❌ 
- HTTP actions URL ❌ 

![Image](https://github.com/user-attachments/assets/c74cf57f-ad1b-4f9f-a2eb-e2433d4addb5)

**Comment by Cinzya** [comment]
@Karnak19 I made the devs aware of it, they are taking a look at it again. Thanks for pointing out.

**Comment by mariusfriess** [comment]
@Cinzya Should this issue have been closed? It appears to have been closed automatically after merging the latest release, but no new commits have addressed the additional issues mentioned in the comments. 

Since those follow-up issues are still unresolved, this probably needs reopening, no?

**Comment by Cinzya** [comment]
@mariusfriess as far as I can tell, the latest commit was by Andras https://github.com/coollabsio/coolify/commit/2ffb93ecdb8caf33e80b37864e96e7fd0622983b, applying the change mentioned by Karnak, reverting the Environment variables back to the FQDN ones.

**Comment by mariusfriess** [comment]
@Cinzya yeah, seems like a miss on my part. Sorry!
