### ISSUE TITLE
[Bug]: Traefik problem from newer than v4.0.0-beta.409 (for ex.: latest v4.0.0-beta.414)

### ISSUE THREAD

**Issue by oregapam** [coollabsio/coolify#5720]
### Error Message and Logs

Hello,
I installed my first Coolify server to a VPS from Netcup yesterday.
It was v4.0.0-beta.409.

OS: Ubuntu 24.04 and also Debian 12 (tried both)

I followed firstly this guide: https://coolify.io/docs/knowledge-base/cloudflare/tunnels/all-resource

and after this:
https://coolify.io/docs/knowledge-base/cloudflare/tunnels/full-tls

Everything worked well, could deploy from Github ...etc.

Today I got an update reminder to v4.0.0-beta.414 and upgraded.

After restart I can't reach anything from Cloudflare Tunneled domain.

For control panel domain, I get:
502 Bad Gateway
Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared

Cloudflared log:
2025-04-28T19:52:25.806221217Z 2025-04-28T19:52:25Z ERR Request failed error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: tls: failed to verify certificate: x509: certificate is valid for c68564a3c358ea12b665fb18b1026248.e56fd683415f32e0c5d832da62de740a.traefik.default, not grandisapp.my.id" connIndex=1 dest=https://cp.grandisapp.my.id/favicon.ico event=0 ip=198.41.192.7 type=http

Traefik log:
2025-04-28T19:27:51.438257197Z 2025-04-28T19:27:51Z ERR Unable to append certificate /traefik/certs/grandisapp.cert to store error="unable to generate TLS certificate : tls: failed to find any PEM data in certificate input" tlsStoreName=default
2025-04-28T19:27:55.197554076Z 2025-04-28T19:27:55Z ERR Unable to append certificate /traefik/certs/grandisapp.cert to store error="unable to generate TLS certificate : tls: failed to find any PEM data in certificate input" tlsStoreName=default
2025-04-28T19:27:58.100629252Z 2025-04-28T19:27:58Z ERR Unable to obtain ACME certificate for domains error="unable to generate a certificate for the domains [cp.grandisapp.my.id]: error: one or more domains had a problem:\n[cp.grandisapp.my.id] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: 2606:4700:3033::ac43:a473: Invalid response from http://cp.grandisapp.my.id/.well-known/acme-challenge/St3zQ0iMGx0qj0V5sXjWx02lJpqMuZp0n_8_YLrp6eQ: 502\n" ACME CA=https://acme-v02.api.letsencrypt.org/directory acmeCA=https://acme-v02.api.letsencrypt.org/directory domains=["cp.grandisapp.my.id"] providerName=letsencrypt.acme routerName=coolify-realtime-wss@file rule="Host(`cp.grandisapp.my.id`) && PathPrefix(`/app`)"

It looks like the Traefik can't see the created cert and key files like before because in Terminal (coolify-proxy) can't see the certs folder in /Traefik folder.

Please help me.
Thank You

### Steps to Reproduce

1. Install [v4.0.0-beta.414](https://github.com/coollabsio/coolify/releases/tag/v4.0.0-beta.414)
2. Use https://coolify.io/docs/knowledge-base/cloudflare/tunnels/all-resource
3. Use https://coolify.io/docs/knowledge-base/cloudflare/tunnels/full-tls
4. Try to set https://something.domain.tld for control panel url

### Coolify Version

v4.0.0-beta.414

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04 and Debian 12

**Comment by oregapam** [comment]
Also another news.
I purged my VPS and fresh installed to Debian 12, v4.0.0-beta.409 (curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash -s 4.0.0-beta.409).
Everything now works like before.

Also note:
If you upgrade from v4.0.0-beta.409 to newer, the downgrading also neither work and the nor the uninstalling procedure.
Only the OS reinstall helps.

**Comment by djsisson** [comment]
@oregapam I'm wondering if this is a permission issue on the folder.

Can you check what you see from inside the traefik container, before and after a chmod on the folder

Alternatively you can add a volume mount to traefik that is outside /data so won't be affected by coolify

**Comment by pascalElyxoft** [comment]
We have the same problem here (same title this is why I am not creating a new one, but not with CloudFlare).
When upgrading yesterday to 414 from v4.0.0-beta.40x (don't remember the exact number, last upgrade 2 or 3 weeks ago).
When I go to the Dynamic Configurations, I do not see any of my previous configurations, only coolify.yaml .
After researches I see that in the traefik docker_compose file, the volume has been changed from : 
`      - '/data/coolify/proxy:/traefik'`
to
`      - '/:/traefik'`
which is a very big problem. Now in my /, I have a docker-compose.yml (the traefik one) and a dynamic/ directory.

Important note : Before Upgrading Coolify, I have done a apt-get update+upgrade and a reboot because of an update of the kernel from OVH VPS, now the kernel is : GNU/Linux 6.11.0-24-generic x86_64

After changing back the docker_compose and restarted the proxy, the Dynamic Configurations has 2 more files : Caddyfile and default_redirect_503.yaml and if I check on my VPS, it is inside the /dynamic/ directory. In my /data/coolify/proxy/dynamic, I have 2 more files for others applications (like nextcloud-aio.yaml for the nextcloud-aio install, outside of coolify but where I need to setup the reverse proxy).

The very strange thing is that the reverse proxy for our nextcloud is working fine (fortunately), so maybe now it's just a problem with the display infos in the Dynamic Configurations. But I'm not sure if what I have done is the proper way to fix it and if others things will go wrong (like the problem of oregapam below). And I cannot rollback or reinstall the VPS.

Hope this helps.

### Example Repository URL

No response

### Coolify Version

v4.0.0-beta.414

### Are you using Coolify Cloud?

No (self-hosted on OVH VPS)

### Operating System and Version (self-hosted)

Ubuntu 24.10 (GNU/Linux 6.11.0-24-generic x86_64)

### Additional Information

No response

**Comment by JCluzet** [comment]
same issue here :/

**Comment by djsisson** [comment]
this has been fixed in 415

**Comment by oregapam** [comment]
@djsisson thank you for the fast response.

I tried to chmod but nothing happens.

Also I wrote that yesterday completely reinstalled the OS and the 409 version and worked well.

At morning the without any change by me, Traefik stopped to give logs and the Cloudflare tunneled domain stopped work (cloudflared docker resource still works)

After that I upgraded to latest version of coolify, but the Traefik still don't work and also got the problem that coolify-proxy can't see the certs folder.

Now the whole thing is useless with cloudflare tunneling.

Are there any plus setting that I can try?

Thank You

**Comment by djsisson** [comment]
@oregapam when you can upgrade to 415 it should now be fixed

**Comment by pascalElyxoft** [comment]
> this has been fixed in 415

Worked for me. Upgrading to 415 fix the problem : Dynamic Configurations now display all my files in /data/coolify/proxy .
In my case, I have also remove the bad files created in : /dynamic/* and /docker-compose.yml 
Thanks @djsisson

**Comment by oregapam** [comment]
@djsisson Yes, now the coolify-proxy see the /data/coolify/proxy folder's contents.

I reinstalled everything from zero and the 2nd problem still exists.

After I made everything for full TLS tunneling and want to set the cp url, I get DNS problems:

![Image](https://github.com/user-attachments/assets/24e02ec1-e5e9-4d06-8f53-828a7d73d299)

Also have no logs in Traefik:

![Image](https://github.com/user-attachments/assets/ebd8cce9-6c74-4959-a7ad-523209127b6b)

I get DNS_PROBE_FINISHED_NXDOMAIN error when I try to reach the subdomain:

![Image](https://github.com/user-attachments/assets/ad5cfdce-bbcc-4637-9465-536611beee8d)

And the CloudFlared logs:

```
2025-04-29T15:10:33.951233219Z 2025-04-29T15:10:33Z INF Starting tunnel tunnelID=863fd369-30fb-4bd1-90c1-fb234398dbb5
2025-04-29T15:10:33.951441334Z 2025-04-29T15:10:33Z INF Version 2025.4.0 (Checksum 7bec9d5632a9983230f7a30f287ce002d7944ba6b2eb9cf4252664e19d9b1c94)
2025-04-29T15:10:33.951457205Z 2025-04-29T15:10:33Z INF GOOS: linux, GOVersion: go1.22.5-devel-cf, GoArch: amd64
2025-04-29T15:10:33.951547281Z 2025-04-29T15:10:33Z INF Settings: map[no-autoupdate:true]
2025-04-29T15:10:33.951638419Z 2025-04-29T15:10:33Z INF Environmental variables map[CLOUDFLARE_TUNNEL_TOKEN:eyJhIjoiNDZlZGVkM2JlZmU4OGVlZGEwOTEzMjQ4ODY1M2I2YzkiLCJ0IjoiODYzZmQzNjktMzBmYi00YmQxLTkwYzEtZmIyMzQzOThkYmI1IiwicyI6Ik1HUXpZamRtT0RRdE9XTm1PUzAwWkRFNExUazFOVFV0WXprNU4yVTBOelF4TUdReSJ9 TUNNEL_TOKEN:*****]
2025-04-29T15:10:33.952697412Z 2025-04-29T15:10:33Z INF Generated Connector ID: c931e153-8e92-460a-8849-3d46717df581
2025-04-29T15:10:33.957722274Z 2025-04-29T15:10:33Z INF Initial protocol quic
2025-04-29T15:10:33.965530279Z 2025-04-29T15:10:33Z INF ICMP proxy will use 213.109.162.151 as source for IPv4
2025-04-29T15:10:33.965774175Z 2025-04-29T15:10:33Z INF ICMP proxy will use 2a03:4000:36:d00:4485:7fff:fefe:3011 in zone eth0 as source for IPv6
2025-04-29T15:10:33.965921812Z 2025-04-29T15:10:33Z WRN The user running cloudflared process has a GID (group ID) that is not within ping_group_range. You might need to add that user to a group within that range, or instead update the range to encompass a group the user is already in by modifying /proc/sys/net/ipv4/ping_group_range. Otherwise cloudflared will not be able to ping this network error="Group ID 65532 is not between ping group 1 to 0"
2025-04-29T15:10:33.965971980Z 2025-04-29T15:10:33Z WRN ICMP proxy feature is disabled error="cannot create ICMPv4 proxy: Group ID 65532 is not between ping group 1 to 0 nor ICMPv6 proxy: socket: permission denied"
2025-04-29T15:10:33.970384619Z 2025-04-29T15:10:33Z INF ICMP proxy will use 213.109.162.151 as source for IPv4
2025-04-29T15:10:33.970697719Z 2025-04-29T15:10:33Z INF ICMP proxy will use 2a03:4000:36:d00:4485:7fff:fefe:3011 in zone eth0 as source for IPv6
2025-04-29T15:10:33.971102618Z 2025-04-29T15:10:33Z INF Starting metrics server on [::]:20241/metrics
2025-04-29T15:10:33.972756080Z 2025-04-29T15:10:33Z INF Using [CurveID(4588) CurveID(25497) CurveP256] as curve preferences connIndex=0 event=0 ip=198.41.192.57
2025-04-29T15:10:34.181795411Z 2025-04-29T15:10:34Z INF Registered tunnel connection connIndex=0 connection=3447bbb0-06ee-4abc-8dd0-e1ce57f8f824 event=0 ip=198.41.192.57 location=fra08 protocol=quic
2025-04-29T15:10:34.181838435Z 2025-04-29T15:10:34Z INF Using [CurveID(4588) CurveID(25497) CurveP256] as curve preferences connIndex=1 event=0 ip=198.41.200.113
2025-04-29T15:10:34.367166230Z 2025-04-29T15:10:34Z INF Registered tunnel connection connIndex=1 connection=1704bffa-84c1-49e4-8c6e-b1951f26b15f event=0 ip=198.41.200.113 location=fra16 protocol=quic
2025-04-29T15:10:35.182933212Z 2025-04-29T15:10:35Z INF Using [CurveID(4588) CurveID(25497) CurveP256] as curve preferences connIndex=2 event=0 ip=198.41.200.23
2025-04-29T15:10:35.407632130Z 2025-04-29T15:10:35Z INF Registered tunnel connection connIndex=2 connection=7ac0d78b-5134-4129-b361-3aa8e606d0f6 event=0 ip=198.41.200.23 location=fra20 protocol=quic
2025-04-29T15:10:36.183611893Z 2025-04-29T15:10:36Z INF Using [CurveID(4588) CurveID(25497) CurveP256] as curve preferences connIndex=3 event=0 ip=198.41.192.77
2025-04-29T15:10:36.674644805Z 2025-04-29T15:10:36Z INF Registered tunnel connection connIndex=3 connection=1efa2b8f-a7c8-44ff-a0a3-536c4f1c4e2d event=0 ip=198.41.192.77 location=fra11 protocol=quic
2025-04-29T15:12:27.874818688Z 2025-04-29T15:12:27Z INF Updated to new configuration config="{\"ingress\":[{\"hostname\":\"*.grandisapp.my.id\", \"originRequest\":{\"originServerName\":\"grandisapp.my.id\"}, \"service\":\"https://localhost:443\"}, {\"service\":\"http_status:404\"}], \"warp-routing\":{\"enabled\":false}}" version=1
2025-04-29T15:12:42.204042342Z 2025-04-29T15:12:42Z INF Initiating graceful shutdown due to signal terminated ...
2025-04-29T15:12:42.414441288Z 2025-04-29T15:12:42Z ERR Failed to serve tunnel connection error="Application error 0x0 (remote)" connIndex=2 event=0 ip=198.41.200.23
2025-04-29T15:12:42.414467248Z 2025-04-29T15:12:42Z ERR Serve tunnel error error="Application error 0x0 (remote)" connIndex=2 event=0 ip=198.41.200.23
2025-04-29T15:12:42.414471386Z 2025-04-29T15:12:42Z INF Retrying connection in up to 1s connIndex=2 event=0 ip=198.41.200.23
2025-04-29T15:12:42.468525589Z 2025-04-29T15:12:42Z ERR Failed to serve tunnel connection error="Application error 0x0 (remote)" connIndex=3 event=0 ip=198.41.192.77
2025-04-29T15:12:42.468560345Z 2025-04-29T15:12:42Z ERR Serve tunnel error error="Application error 0x0 (remote)" connIndex=3 event=0 ip=198.41.192.77
2025-04-29T15:12:42.468563942Z 2025-04-29T15:12:42Z INF Retrying connection in up to 1s connIndex=3 event=0 ip=198.41.192.77
2025-04-29T15:12:42.681868451Z 2025-04-29T15:12:42Z ERR Failed to serve tunnel connection error="Application error 0x0 (remote)" connIndex=1 event=0 ip=198.41.200.113
2025-04-29T15:12:42.681917193Z 2025-04-29T15:12:42Z ERR Serve tunnel error error="Application error 0x0 (remote)" connIndex=1 event=0 ip=198.41.200.113
2025-04-29T15:12:42.681921481Z 2025-04-29T15:12:42Z INF Retrying connection in up to 1s connIndex=1 event=0 ip=198.41.200.113
2025-04-29T15:12:42.784327863Z 2025-04-29T15:12:42Z ERR Failed to serve tunnel connection error="context canceled" connIndex=0 event=0 ip=198.41.192.57
2025-04-29T15:12:42.784357981Z 2025-04-29T15:12:42Z INF Retrying connection in up to 1s connIndex=0 event=0 ip=198.41.192.57
2025-04-29T15:12:42.784361788Z 2025-04-29T15:12:42Z ERR no more connections active and exiting
2025-04-29T15:12:42.784365044Z 2025-04-29T15:12:42Z INF Tunnel server stopped
2025-04-29T15:12:42.784433695Z 2025-04-29T15:12:42Z INF Metrics server stopped
2025-04-29T15:13:12.083813581Z 2025-04-29T15:13:12Z INF Starting tunnel tunnelID=863fd369-30fb-4bd1-90c1-fb234398dbb5
2025-04-29T15:13:12.093881743Z 2025-04-29T15:13:12Z INF Version 2025.4.0 (Checksum 7bec9d5632a9983230f7a30f287ce002d7944ba6b2eb9cf4252664e19d9b1c94)
2025-04-29T15:13:12.093907562Z 2025-04-29T15:13:12Z INF GOOS: linux, GOVersion: go1.22.5-devel-cf, GoArch: amd64
2025-04-29T15:13:12.093911479Z 2025-04-29T15:13:12Z INF Settings: map[no-autoupdate:true]
2025-04-29T15:13:12.093915176Z 2025-04-29T15:13:12Z INF Environmental variables map[CLOUDFLARE_TUNNEL_TOKEN:eyJhIjoiNDZlZGVkM2JlZmU4OGVlZGEwOTEzMjQ4ODY1M2I2YzkiLCJ0IjoiODYzZmQzNjktMzBmYi00YmQxLTkwYzEtZmIyMzQzOThkYmI1IiwicyI6Ik1HUXpZamRtT0RRdE9XTm1PUzAwWkRFNExUazFOVFV0WXprNU4yVTBOelF4TUdReSJ9 TUNNEL_TOKEN:*****]
2025-04-29T15:13:12.093930685Z 2025-04-29T15:13:12Z INF Generated Connector ID: 04e539fc-a5e2-4090-a99b-a8ae178bd07e
2025-04-29T15:13:12.093933741Z 2025-04-29T15:13:12Z INF Initial protocol quic
2025-04-29T15:13:12.212754760Z 2025-04-29T15:13:12Z INF ICMP proxy will use 213.109.162.151 as source for IPv4
2025-04-29T15:13:12.212933355Z 2025-04-29T15:13:12Z INF ICMP proxy will use 2a03:4000:36:d00:4485:7fff:fefe:3011 in zone eth0 as source for IPv6
2025-04-29T15:13:12.213095679Z 2025-04-29T15:13:12Z WRN The user running cloudflared process has a GID (group ID) that is not within ping_group_range. You might need to add that user to a group within that range, or instead update the range to encompass a group the user is already in by modifying /proc/sys/net/ipv4/ping_group_range. Otherwise cloudflared will not be able to ping this network error="Group ID 65532 is not between ping group 1 to 0"
2025-04-29T15:13:12.213141665Z 2025-04-29T15:13:12Z WRN ICMP proxy feature is disabled error="cannot create ICMPv4 proxy: Group ID 65532 is not between ping group 1 to 0 nor ICMPv6 proxy: socket: permission denied"
2025-04-29T15:13:12.219696639Z 2025-04-29T15:13:12Z INF ICMP proxy will use 213.109.162.151 as source for IPv4
2025-04-29T15:13:12.219989468Z 2025-04-29T15:13:12Z INF ICMP proxy will use 2a03:4000:36:d00:4485:7fff:fefe:3011 in zone eth0 as source for IPv6
2025-04-29T15:13:12.220088164Z 2025-04-29T15:13:12Z INF Starting metrics server on [::]:20241/metrics
2025-04-29T15:13:12.227113079Z 2025-04-29T15:13:12Z INF Using [CurveID(4588) CurveID(25497) CurveP256] as curve preferences connIndex=0 event=0 ip=198.41.192.57
2025-04-29T15:13:12.454524459Z 2025-04-29T15:13:12Z INF Registered tunnel connection connIndex=0 connection=763d316c-98ed-4dd5-8095-04064c98a3a1 event=0 ip=198.41.192.57 location=fra03 protocol=quic
2025-04-29T15:13:12.454567139Z 2025-04-29T15:13:12Z INF Using [CurveID(4588) CurveID(25497) CurveP256] as curve preferences connIndex=1 event=0 ip=198.41.200.233
2025-04-29T15:13:12.459269829Z 2025-04-29T15:13:12Z INF Updated to new configuration config="{\"ingress\":[{\"hostname\":\"*.grandisapp.my.id\", \"originRequest\":{\"originServerName\":\"grandisapp.my.id\"}, \"service\":\"https://localhost:443\"}, {\"service\":\"http_status:404\"}], \"warp-routing\":{\"enabled\":false}}" version=1
2025-04-29T15:13:13.013751549Z 2025-04-29T15:13:13Z INF Registered tunnel connection connIndex=1 connection=e789b43e-06b5-421c-bf74-6989550519bb event=0 ip=198.41.200.233 location=fra15 protocol=quic
2025-04-29T15:13:13.454781891Z 2025-04-29T15:13:13Z INF Using [CurveID(4588) CurveID(25497) CurveP256] as curve preferences connIndex=2 event=0 ip=198.41.200.63
2025-04-29T15:13:14.001143753Z 2025-04-29T15:13:14Z INF Registered tunnel connection connIndex=2 connection=97c4acf8-4aa1-4f5b-9b5f-b163e8c6892b event=0 ip=198.41.200.63 location=fra14 protocol=quic
2025-04-29T15:13:14.456030613Z 2025-04-29T15:13:14Z INF Using [CurveID(4588) CurveID(25497) CurveP256] as curve preferences connIndex=3 event=0 ip=198.41.192.37
2025-04-29T15:13:14.950412817Z 2025-04-29T15:13:14Z INF Registered tunnel connection connIndex=3 connection=908191f6-ebfa-40f3-8d52-f4976a9a19cc event=0 ip=198.41.192.37 location=fra10 protocol=quic
```

This problem was happened also on version 409 today morning, but not exist yesterday night.
It is strange because I don't do anything between yesterday night and today morning.

Can you please help me with this too?
Thank You

**Comment by djsisson** [comment]
@oregapam you need to check what you have in your dns provider, as that domain does not exist

**Comment by oregapam** [comment]
@djsisson You right. That never happened with me before, but the Hostinger suspended my domain after a few days working.

Thank You for the fix and your fast response.
