### ISSUE TITLE
[Bug]: coolify-fluent-bit is AMD64 only.

### ISSUE THREAD

**Issue by Huskehhh** [coollabsio/coolify#681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Running the `coolify-fluent-bit` container on ARM64 (Oracle) results in

```
exec /fluent-bit/bin/fluent-bit: exec format error
```

Upstream `fluent-bit` container supports ARM64, so this should just be a matter of duplicating the workflow to build a multi-arch image upon release

### Steps To Reproduce

1. Run `coolify-fluentbit` on ARM
2. Look at logs

### Version

3.10.16

**Comment by andrasbacsai** [comment]
I have a running version on ARM based server. Can you please show me the logs?

Due to inactivity, I'm closing this issue. However, if the problem persists, please reopen the issue. Thanks!

**Comment by Huskehhh** [comment]
Definitely still a thing.

```
$ exec /fluent-bit/bin/fluent-bit: exec format error
```

https://hub.docker.com/r/coollabsio/coolify-fluent-bit/tags

Look at the arch on the image, you must be using an M1 or M2 with Rosetta.

**Comment by andrasbacsai** [comment]
Fixed it!

![image](https://user-images.githubusercontent.com/5845193/202679945-2cafe0a0-4236-4970-a490-13ffb0017a49.png)

**Comment by Huskehhh** [comment]
> Fixed it! Thanks for the report!
> 
> ![image](https://user-images.githubusercontent.com/5845193/202679945-2cafe0a0-4236-4970-a490-13ffb0017a49.png)

Still no good :(

**Comment by Jokiller230** [comment]
Hey, I am still receiving an exec format error in the fluentbit container on the latest version 3.11.13

Error: `exec /fluent-bit/bin/fluent-bit: exec format error`

**Comment by Jokiller230** [comment]
I was able to fix the issue by manually setting up coolify with the docker-compose & .env file with the latest versions of fluentbit and the main coolify image.

Although it would be cool to have it working with the install script.
