### ISSUE TITLE
[Bug]: "Backup includes all databases" action incorrectly triggers the "Database Restore Output" popup

### ISSUE THREAD

**Issue by NrwPlay** [coollabsio/coolify#7817]
### Error Message and Logs

<img width="497" height="576" alt="Image" src="https://github.com/user-attachments/assets/3e0bb08e-3d5e-4b5b-8bc8-76320aba2c77" />

### Steps to Reproduce

1. Open an MariaDB Database.
2. Click on “Import Backups”.
3. Select the backup option “Backup includes all databases”.
4. You will see an "Database Restore Output" Popup opening, which you cant close.

### Coolify Version

v4.0.0-beta.459

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04.3 LTS

### Additional Information

already had the same bug in #7335  there it got fixed, but now i realized that it is not fixed for MariaDB Databases

**Comment by peaklabs-dev** [comment]
I am unable to reproduce this issue. It has probably been fixed in the latest version.

**Comment by NrwPlay** [comment]
The issue still persists on Coolify v4.0.0-beta.460, the problem currently only occures for MariaDB Databases
