### ISSUE TITLE
[Bug]: environments are not working properly

### ISSUE THREAD

**Issue by ChikoShidori** [coollabsio/coolify#807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

## When I try to deploy an application I get the following error
![image](https://user-images.githubusercontent.com/53100578/209171884-11475b5d-fcf3-4bbd-befa-5c2773b8e69a.png)

I have tried downgrading to 3.12.2 and it works properly.

### Steps To Reproduce

1. Make sure you are using the version 3.12.3 or 3.12.4
2. Try to deploy an application which requires some environments/secrets
3. See the error in the build logs

### Version

3.12.3 & 3.12.4

**Comment by Tiagofv** [comment]
Just submitted a fix on #809

**Comment by vfcandidate** [comment]
It doesn't look like it is fixed in the latest release contrary to the change log 😣

![image](https://user-images.githubusercontent.com/80484052/209652906-d45a0aa2-7e6f-4f34-adab-f1d9608f2f79.png)

**Comment by cruonline** [comment]
It doesn't look like it was fixed in the latest release contrary to the change log... :(
![image](https://user-images.githubusercontent.com/3149188/209653347-16c656ac-d70a-4e09-b4ad-4a561dfb1b1f.png)

**Comment by Tiagofv** [comment]
@cruonline just to confirm, you're still facing this in docker-compose builds or in other types of builds?

**Comment by cruonline** [comment]
docker-compose builds

**Comment by ChikoShidori** [comment]
the bug still exists in version 3.12.8 (latest)

**Comment by codesalatdev** [comment]
Facing the same issue with 3.12.8.

Fixed it temporarily by moving all variables to secrets: 
```conf
environment:
      # see https://ghost.org/docs/config/#configuration-options
      - database__client
      - database__connection__host
      - database__connection__user
```

instead of
```conf
environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: user
```

**Comment by zek** [comment]
Appereantly this issue is not fixed. Currently I'm on v3.12.10

Trying to install following registry https://github.com/repman-io/repman

```
[12:07:18.573] Cloning repman-io/repman:master...
[12:07:19.939] Configuration changed
[12:07:21.176] {}
[12:07:21.181] environment is not iterable
```

This is the error I'm getting

**Comment by cruonline** [comment]
@zek I believe that at this point after so many releases this is now a feature 😉
I am sticking with 3.12.2 until it is fixed. Not sure why this report is closed though...

**Comment by BrianGrug** [comment]
Getting this too as well

**Comment by andrasbacsai** [comment]
Definitely not a feature! 🙂

**Comment by BrianGrug** [comment]
> Definitely not a feature! 🙂
> 
> So this is happening with the docker compose build pack, right?

Yes

**Comment by zek** [comment]
Build time env variables are not working for docker-compose builds.

**Comment by andrasbacsai** [comment]
> Appereantly this issue is not fixed. Currently I'm on v3.12.10
> 
> Trying to install following registry https://github.com/repman-io/repman
> 
> ```
> [12:07:18.573] Cloning repman-io/repman:master...
> [12:07:19.939] Configuration changed
> [12:07:21.176] {}
> [12:07:21.181] environment is not iterable
> ```
> 
> This is the error I'm getting

The next version will have a fix for this!

**Comment by andrasbacsai** [comment]
> Build time env variables are not working for docker-compose builds.

Also adding this to the next version.

**Comment by KoljaL** [comment]
Is there a workaround for this:

```
[12:07:18.573] Cloning repman-io/repman:master...
[12:07:19.939] Configuration changed
[12:07:21.176] {}
[12:07:21.181] environment is not iterable
```
until it will be fixed in the next version?

**Comment by bd-dm** [comment]
> Is there a workaround for this:
> 
> ```
> [12:07:18.573] Cloning repman-io/repman:master...
> [12:07:19.939] Configuration changed
> [12:07:21.176] {}
> [12:07:21.181] environment is not iterable
> ```
> 
> ~until it will be fixed in the next version?~
> 
> Okay, as far as I understand, the version with the fix is released.
> 
> But, for example [this](https://github.com/nickjj/docker-node-example) docker-compose still produces the `environment is not iterable` error.

Hi! I had the same issue and it looks like coolify only works with object in environment property because of this line: https://github.com/coollabsio/coolify/blob/main/apps/api/src/lib/buildPacks/compose.ts#L56

So in order to make it work in current version i had to modify enviroment property from array to object

***Before:***
```yaml
environment:
    - VARIABLE=VALUE
```
***After:***
```yaml
environment:
    VARIABLE: "VALUE"
```

@andrasbacsai FYI

**Comment by masterbater** [comment]
> 

Thats why it didnt work please update it the way docker-compose config is meant to do it. Imagine if we follow this workaround it could cause issue when auto updating coolify with the fix

**Comment by masterbater** [comment]
> > Is there a workaround for this:
> > ```
> > [12:07:18.573] Cloning repman-io/repman:master...
> > [12:07:19.939] Configuration changed
> > [12:07:21.176] {}
> > [12:07:21.181] environment is not iterable
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ~until it will be fixed in the next version?~
> > Okay, as far as I understand, the version with the fix is released.
> > But, for example [this](https://github.com/nickjj/docker-node-example) docker-compose still produces the `environment is not iterable` error.
> 
> Hi! I had the same issue and it looks like coolify only works with object in environment property because of this line: https://github.com/coollabsio/coolify/blob/main/apps/api/src/lib/buildPacks/compose.ts#L56
> 
> So in order to make it work in current version i had to modify enviroment property from array to object
> 
> _**Before:**_
> 
> ```yaml
> environment:
>     - VARIABLE=VALUE
> ```
> 
> _**After:**_
> 
> ```yaml
> environment:
>     VARIABLE: "VALUE"
> ```
> 
> @andrasbacsai FYI

Thats why it didnt work please update it the way docker-compose config is meant to do it. Imagine if we follow this workaround it could cause issue when auto updating coolify with the fix
